apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://prod.sm.eu01.stackit.cloud"
      path: "01ca5493-090c-4ec5-ad68-7e31440f1ade"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: c20uZmExYTJkMDFhYjc3YzhjOWFiYjM0YmI1NjQzZTcyNmNhNmVhYmRiNzgwYTJlOGNjY2NjZmFlNzMyMDU1M2I3Mw==
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
    - secretKey: foobar
      remoteRef:
        key: secret/foo
        property: my-value
