name: prod-stackit-terraform-prj-vpn-fw-test-firewall

on:
  workflow_dispatch:
    inputs:
      terraform-force-unlock:
        default: false
        description: Terraform force unlock
        required: false
        type: boolean
      terraform-force-unlock-id:
        description: Terraform LOCK_ID
        required: false
        type: string
  pull_request:
    paths:
      - prod-stackit/terraform/50_projects/prj-vpn-fw-test-firewall/**
      - .github/workflows/prod-stackit-terraform-prj-vpn-fw-test-firewall.yaml

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform
    uses: cloudeteer/iac-deployment-framework/.github/workflows/terraform-deploy-stackit.yaml@wip/stackit
    with:
      directory: prod-stackit/terraform/50_projects/prj-vpn-fw-test-firewall
      terraform-force-unlock-id: ${{ github.event_name == 'workflow_dispatch' && inputs.terraform-force-unlock == true && inputs.terraform-force-unlock-id }}
      terraform-force-unlock: ${{ github.event_name == 'workflow_dispatch' && inputs.terraform-force-unlock == true && inputs.terraform-force-unlock }}
    secrets:
      stackit_service_account_key: ${{ secrets.CDT_LAUNCHPAD_STACKIT_SERVICE_ACCOUNT_KEY }}
      backend_s3_secret_key: ${{ secrets.CDT_LAUNCHPAD_STACKIT_BACKEND_SECRET_ACCESS_KEY }}
      backend_s3_access_key: ${{ secrets.CDT_LAUNCHPAD_STACKIT_BACKEND_ACCESS_KEY }}
      env: |-
        TF_VAR_PASSWORD: ${{ secrets.CDT_STACKIT_OPENSTACK_UAT_TOKEN_PASSWORD_prj_vpn_fw_test_firewall }}
        TF_VAR_TENANTID: ${{ secrets.CDT_STACKIT_OPENSTACK_PROJECT_ID_prj_vpn_fw_test_firewall }}
        TF_VAR_USERNAME: ${{ secrets.CDT_STACKIT_OPENSTACK_UAT_TOKEN_NAME_prj_vpn_fw_test_firewall }}
